// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spark.proto

package org.training.spark.proto;

public final class Spark {
  private Spark() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewClickEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 userId = 1;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int64 userId = 1;</code>
     */
    long getUserId();

    // optional int64 itemId = 2;
    /**
     * <code>optional int64 itemId = 2;</code>
     */
    boolean hasItemId();
    /**
     * <code>optional int64 itemId = 2;</code>
     */
    long getItemId();
  }
  /**
   * Protobuf type {@code NewClickEvent}
   */
  public static final class NewClickEvent extends
      com.google.protobuf.GeneratedMessage
      implements NewClickEventOrBuilder {
    // Use NewClickEvent.newBuilder() to construct.
    private NewClickEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NewClickEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NewClickEvent defaultInstance;
    public static NewClickEvent getDefaultInstance() {
      return defaultInstance;
    }

    public NewClickEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NewClickEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              itemId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.training.spark.proto.Spark.internal_static_NewClickEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.training.spark.proto.Spark.internal_static_NewClickEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.training.spark.proto.Spark.NewClickEvent.class, org.training.spark.proto.Spark.NewClickEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<NewClickEvent> PARSER =
        new com.google.protobuf.AbstractParser<NewClickEvent>() {
      public NewClickEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewClickEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewClickEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    // optional int64 itemId = 2;
    public static final int ITEMID_FIELD_NUMBER = 2;
    private long itemId_;
    /**
     * <code>optional int64 itemId = 2;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 itemId = 2;</code>
     */
    public long getItemId() {
      return itemId_;
    }

    private void initFields() {
      userId_ = 0L;
      itemId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, itemId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, itemId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.NewClickEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.training.spark.proto.Spark.NewClickEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NewClickEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.training.spark.proto.Spark.NewClickEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.training.spark.proto.Spark.internal_static_NewClickEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.training.spark.proto.Spark.internal_static_NewClickEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.training.spark.proto.Spark.NewClickEvent.class, org.training.spark.proto.Spark.NewClickEvent.Builder.class);
      }

      // Construct using org.training.spark.proto.Spark.NewClickEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.training.spark.proto.Spark.internal_static_NewClickEvent_descriptor;
      }

      public org.training.spark.proto.Spark.NewClickEvent getDefaultInstanceForType() {
        return org.training.spark.proto.Spark.NewClickEvent.getDefaultInstance();
      }

      public org.training.spark.proto.Spark.NewClickEvent build() {
        org.training.spark.proto.Spark.NewClickEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.training.spark.proto.Spark.NewClickEvent buildPartial() {
        org.training.spark.proto.Spark.NewClickEvent result = new org.training.spark.proto.Spark.NewClickEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemId_ = itemId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.training.spark.proto.Spark.NewClickEvent) {
          return mergeFrom((org.training.spark.proto.Spark.NewClickEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.training.spark.proto.Spark.NewClickEvent other) {
        if (other == org.training.spark.proto.Spark.NewClickEvent.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.training.spark.proto.Spark.NewClickEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.training.spark.proto.Spark.NewClickEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 userId = 1;
      private long userId_ ;
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 itemId = 2;
      private long itemId_ ;
      /**
       * <code>optional int64 itemId = 2;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 itemId = 2;</code>
       */
      public long getItemId() {
        return itemId_;
      }
      /**
       * <code>optional int64 itemId = 2;</code>
       */
      public Builder setItemId(long value) {
        bitField0_ |= 0x00000002;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 itemId = 2;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NewClickEvent)
    }

    static {
      defaultInstance = new NewClickEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewClickEvent)
  }

  public interface ItemSimilaritiesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ItemSimilarity itemSimilarites = 1;
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    java.util.List<org.training.spark.proto.Spark.ItemSimilarity> 
        getItemSimilaritesList();
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    org.training.spark.proto.Spark.ItemSimilarity getItemSimilarites(int index);
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    int getItemSimilaritesCount();
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    java.util.List<? extends org.training.spark.proto.Spark.ItemSimilarityOrBuilder> 
        getItemSimilaritesOrBuilderList();
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    org.training.spark.proto.Spark.ItemSimilarityOrBuilder getItemSimilaritesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ItemSimilarities}
   */
  public static final class ItemSimilarities extends
      com.google.protobuf.GeneratedMessage
      implements ItemSimilaritiesOrBuilder {
    // Use ItemSimilarities.newBuilder() to construct.
    private ItemSimilarities(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemSimilarities(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemSimilarities defaultInstance;
    public static ItemSimilarities getDefaultInstance() {
      return defaultInstance;
    }

    public ItemSimilarities getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemSimilarities(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemSimilarites_ = new java.util.ArrayList<org.training.spark.proto.Spark.ItemSimilarity>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemSimilarites_.add(input.readMessage(org.training.spark.proto.Spark.ItemSimilarity.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemSimilarites_ = java.util.Collections.unmodifiableList(itemSimilarites_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.training.spark.proto.Spark.internal_static_ItemSimilarities_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.training.spark.proto.Spark.internal_static_ItemSimilarities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.training.spark.proto.Spark.ItemSimilarities.class, org.training.spark.proto.Spark.ItemSimilarities.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemSimilarities> PARSER =
        new com.google.protobuf.AbstractParser<ItemSimilarities>() {
      public ItemSimilarities parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemSimilarities(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemSimilarities> getParserForType() {
      return PARSER;
    }

    // repeated .ItemSimilarity itemSimilarites = 1;
    public static final int ITEMSIMILARITES_FIELD_NUMBER = 1;
    private java.util.List<org.training.spark.proto.Spark.ItemSimilarity> itemSimilarites_;
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    public java.util.List<org.training.spark.proto.Spark.ItemSimilarity> getItemSimilaritesList() {
      return itemSimilarites_;
    }
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    public java.util.List<? extends org.training.spark.proto.Spark.ItemSimilarityOrBuilder> 
        getItemSimilaritesOrBuilderList() {
      return itemSimilarites_;
    }
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    public int getItemSimilaritesCount() {
      return itemSimilarites_.size();
    }
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    public org.training.spark.proto.Spark.ItemSimilarity getItemSimilarites(int index) {
      return itemSimilarites_.get(index);
    }
    /**
     * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
     */
    public org.training.spark.proto.Spark.ItemSimilarityOrBuilder getItemSimilaritesOrBuilder(
        int index) {
      return itemSimilarites_.get(index);
    }

    private void initFields() {
      itemSimilarites_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < itemSimilarites_.size(); i++) {
        output.writeMessage(1, itemSimilarites_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < itemSimilarites_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, itemSimilarites_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemSimilarities parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.training.spark.proto.Spark.ItemSimilarities prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemSimilarities}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.training.spark.proto.Spark.ItemSimilaritiesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.training.spark.proto.Spark.internal_static_ItemSimilarities_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.training.spark.proto.Spark.internal_static_ItemSimilarities_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.training.spark.proto.Spark.ItemSimilarities.class, org.training.spark.proto.Spark.ItemSimilarities.Builder.class);
      }

      // Construct using org.training.spark.proto.Spark.ItemSimilarities.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemSimilaritesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemSimilaritesBuilder_ == null) {
          itemSimilarites_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemSimilaritesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.training.spark.proto.Spark.internal_static_ItemSimilarities_descriptor;
      }

      public org.training.spark.proto.Spark.ItemSimilarities getDefaultInstanceForType() {
        return org.training.spark.proto.Spark.ItemSimilarities.getDefaultInstance();
      }

      public org.training.spark.proto.Spark.ItemSimilarities build() {
        org.training.spark.proto.Spark.ItemSimilarities result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.training.spark.proto.Spark.ItemSimilarities buildPartial() {
        org.training.spark.proto.Spark.ItemSimilarities result = new org.training.spark.proto.Spark.ItemSimilarities(this);
        int from_bitField0_ = bitField0_;
        if (itemSimilaritesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            itemSimilarites_ = java.util.Collections.unmodifiableList(itemSimilarites_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.itemSimilarites_ = itemSimilarites_;
        } else {
          result.itemSimilarites_ = itemSimilaritesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.training.spark.proto.Spark.ItemSimilarities) {
          return mergeFrom((org.training.spark.proto.Spark.ItemSimilarities)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.training.spark.proto.Spark.ItemSimilarities other) {
        if (other == org.training.spark.proto.Spark.ItemSimilarities.getDefaultInstance()) return this;
        if (itemSimilaritesBuilder_ == null) {
          if (!other.itemSimilarites_.isEmpty()) {
            if (itemSimilarites_.isEmpty()) {
              itemSimilarites_ = other.itemSimilarites_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemSimilaritesIsMutable();
              itemSimilarites_.addAll(other.itemSimilarites_);
            }
            onChanged();
          }
        } else {
          if (!other.itemSimilarites_.isEmpty()) {
            if (itemSimilaritesBuilder_.isEmpty()) {
              itemSimilaritesBuilder_.dispose();
              itemSimilaritesBuilder_ = null;
              itemSimilarites_ = other.itemSimilarites_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemSimilaritesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemSimilaritesFieldBuilder() : null;
            } else {
              itemSimilaritesBuilder_.addAllMessages(other.itemSimilarites_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.training.spark.proto.Spark.ItemSimilarities parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.training.spark.proto.Spark.ItemSimilarities) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ItemSimilarity itemSimilarites = 1;
      private java.util.List<org.training.spark.proto.Spark.ItemSimilarity> itemSimilarites_ =
        java.util.Collections.emptyList();
      private void ensureItemSimilaritesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemSimilarites_ = new java.util.ArrayList<org.training.spark.proto.Spark.ItemSimilarity>(itemSimilarites_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.training.spark.proto.Spark.ItemSimilarity, org.training.spark.proto.Spark.ItemSimilarity.Builder, org.training.spark.proto.Spark.ItemSimilarityOrBuilder> itemSimilaritesBuilder_;

      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public java.util.List<org.training.spark.proto.Spark.ItemSimilarity> getItemSimilaritesList() {
        if (itemSimilaritesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(itemSimilarites_);
        } else {
          return itemSimilaritesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public int getItemSimilaritesCount() {
        if (itemSimilaritesBuilder_ == null) {
          return itemSimilarites_.size();
        } else {
          return itemSimilaritesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public org.training.spark.proto.Spark.ItemSimilarity getItemSimilarites(int index) {
        if (itemSimilaritesBuilder_ == null) {
          return itemSimilarites_.get(index);
        } else {
          return itemSimilaritesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder setItemSimilarites(
          int index, org.training.spark.proto.Spark.ItemSimilarity value) {
        if (itemSimilaritesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.set(index, value);
          onChanged();
        } else {
          itemSimilaritesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder setItemSimilarites(
          int index, org.training.spark.proto.Spark.ItemSimilarity.Builder builderForValue) {
        if (itemSimilaritesBuilder_ == null) {
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemSimilaritesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder addItemSimilarites(org.training.spark.proto.Spark.ItemSimilarity value) {
        if (itemSimilaritesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.add(value);
          onChanged();
        } else {
          itemSimilaritesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder addItemSimilarites(
          int index, org.training.spark.proto.Spark.ItemSimilarity value) {
        if (itemSimilaritesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.add(index, value);
          onChanged();
        } else {
          itemSimilaritesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder addItemSimilarites(
          org.training.spark.proto.Spark.ItemSimilarity.Builder builderForValue) {
        if (itemSimilaritesBuilder_ == null) {
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.add(builderForValue.build());
          onChanged();
        } else {
          itemSimilaritesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder addItemSimilarites(
          int index, org.training.spark.proto.Spark.ItemSimilarity.Builder builderForValue) {
        if (itemSimilaritesBuilder_ == null) {
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemSimilaritesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder addAllItemSimilarites(
          java.lang.Iterable<? extends org.training.spark.proto.Spark.ItemSimilarity> values) {
        if (itemSimilaritesBuilder_ == null) {
          ensureItemSimilaritesIsMutable();
          super.addAll(values, itemSimilarites_);
          onChanged();
        } else {
          itemSimilaritesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder clearItemSimilarites() {
        if (itemSimilaritesBuilder_ == null) {
          itemSimilarites_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemSimilaritesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public Builder removeItemSimilarites(int index) {
        if (itemSimilaritesBuilder_ == null) {
          ensureItemSimilaritesIsMutable();
          itemSimilarites_.remove(index);
          onChanged();
        } else {
          itemSimilaritesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public org.training.spark.proto.Spark.ItemSimilarity.Builder getItemSimilaritesBuilder(
          int index) {
        return getItemSimilaritesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public org.training.spark.proto.Spark.ItemSimilarityOrBuilder getItemSimilaritesOrBuilder(
          int index) {
        if (itemSimilaritesBuilder_ == null) {
          return itemSimilarites_.get(index);  } else {
          return itemSimilaritesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public java.util.List<? extends org.training.spark.proto.Spark.ItemSimilarityOrBuilder> 
           getItemSimilaritesOrBuilderList() {
        if (itemSimilaritesBuilder_ != null) {
          return itemSimilaritesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(itemSimilarites_);
        }
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public org.training.spark.proto.Spark.ItemSimilarity.Builder addItemSimilaritesBuilder() {
        return getItemSimilaritesFieldBuilder().addBuilder(
            org.training.spark.proto.Spark.ItemSimilarity.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public org.training.spark.proto.Spark.ItemSimilarity.Builder addItemSimilaritesBuilder(
          int index) {
        return getItemSimilaritesFieldBuilder().addBuilder(
            index, org.training.spark.proto.Spark.ItemSimilarity.getDefaultInstance());
      }
      /**
       * <code>repeated .ItemSimilarity itemSimilarites = 1;</code>
       */
      public java.util.List<org.training.spark.proto.Spark.ItemSimilarity.Builder> 
           getItemSimilaritesBuilderList() {
        return getItemSimilaritesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.training.spark.proto.Spark.ItemSimilarity, org.training.spark.proto.Spark.ItemSimilarity.Builder, org.training.spark.proto.Spark.ItemSimilarityOrBuilder> 
          getItemSimilaritesFieldBuilder() {
        if (itemSimilaritesBuilder_ == null) {
          itemSimilaritesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.training.spark.proto.Spark.ItemSimilarity, org.training.spark.proto.Spark.ItemSimilarity.Builder, org.training.spark.proto.Spark.ItemSimilarityOrBuilder>(
                  itemSimilarites_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          itemSimilarites_ = null;
        }
        return itemSimilaritesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ItemSimilarities)
    }

    static {
      defaultInstance = new ItemSimilarities(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemSimilarities)
  }

  public interface ItemSimilarityOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 itemId = 1;
    /**
     * <code>optional int64 itemId = 1;</code>
     */
    boolean hasItemId();
    /**
     * <code>optional int64 itemId = 1;</code>
     */
    long getItemId();

    // optional double similarity = 2;
    /**
     * <code>optional double similarity = 2;</code>
     */
    boolean hasSimilarity();
    /**
     * <code>optional double similarity = 2;</code>
     */
    double getSimilarity();
  }
  /**
   * Protobuf type {@code ItemSimilarity}
   */
  public static final class ItemSimilarity extends
      com.google.protobuf.GeneratedMessage
      implements ItemSimilarityOrBuilder {
    // Use ItemSimilarity.newBuilder() to construct.
    private ItemSimilarity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemSimilarity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemSimilarity defaultInstance;
    public static ItemSimilarity getDefaultInstance() {
      return defaultInstance;
    }

    public ItemSimilarity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemSimilarity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              itemId_ = input.readInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              similarity_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.training.spark.proto.Spark.internal_static_ItemSimilarity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.training.spark.proto.Spark.internal_static_ItemSimilarity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.training.spark.proto.Spark.ItemSimilarity.class, org.training.spark.proto.Spark.ItemSimilarity.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemSimilarity> PARSER =
        new com.google.protobuf.AbstractParser<ItemSimilarity>() {
      public ItemSimilarity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemSimilarity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemSimilarity> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 itemId = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private long itemId_;
    /**
     * <code>optional int64 itemId = 1;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 itemId = 1;</code>
     */
    public long getItemId() {
      return itemId_;
    }

    // optional double similarity = 2;
    public static final int SIMILARITY_FIELD_NUMBER = 2;
    private double similarity_;
    /**
     * <code>optional double similarity = 2;</code>
     */
    public boolean hasSimilarity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double similarity = 2;</code>
     */
    public double getSimilarity() {
      return similarity_;
    }

    private void initFields() {
      itemId_ = 0L;
      similarity_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, similarity_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, itemId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, similarity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemSimilarity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.training.spark.proto.Spark.ItemSimilarity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemSimilarity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.training.spark.proto.Spark.ItemSimilarityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.training.spark.proto.Spark.internal_static_ItemSimilarity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.training.spark.proto.Spark.internal_static_ItemSimilarity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.training.spark.proto.Spark.ItemSimilarity.class, org.training.spark.proto.Spark.ItemSimilarity.Builder.class);
      }

      // Construct using org.training.spark.proto.Spark.ItemSimilarity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        similarity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.training.spark.proto.Spark.internal_static_ItemSimilarity_descriptor;
      }

      public org.training.spark.proto.Spark.ItemSimilarity getDefaultInstanceForType() {
        return org.training.spark.proto.Spark.ItemSimilarity.getDefaultInstance();
      }

      public org.training.spark.proto.Spark.ItemSimilarity build() {
        org.training.spark.proto.Spark.ItemSimilarity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.training.spark.proto.Spark.ItemSimilarity buildPartial() {
        org.training.spark.proto.Spark.ItemSimilarity result = new org.training.spark.proto.Spark.ItemSimilarity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.similarity_ = similarity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.training.spark.proto.Spark.ItemSimilarity) {
          return mergeFrom((org.training.spark.proto.Spark.ItemSimilarity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.training.spark.proto.Spark.ItemSimilarity other) {
        if (other == org.training.spark.proto.Spark.ItemSimilarity.getDefaultInstance()) return this;
        if (other.hasItemId()) {
          setItemId(other.getItemId());
        }
        if (other.hasSimilarity()) {
          setSimilarity(other.getSimilarity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.training.spark.proto.Spark.ItemSimilarity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.training.spark.proto.Spark.ItemSimilarity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 itemId = 1;
      private long itemId_ ;
      /**
       * <code>optional int64 itemId = 1;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 itemId = 1;</code>
       */
      public long getItemId() {
        return itemId_;
      }
      /**
       * <code>optional int64 itemId = 1;</code>
       */
      public Builder setItemId(long value) {
        bitField0_ |= 0x00000001;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 itemId = 1;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = 0L;
        onChanged();
        return this;
      }

      // optional double similarity = 2;
      private double similarity_ ;
      /**
       * <code>optional double similarity = 2;</code>
       */
      public boolean hasSimilarity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double similarity = 2;</code>
       */
      public double getSimilarity() {
        return similarity_;
      }
      /**
       * <code>optional double similarity = 2;</code>
       */
      public Builder setSimilarity(double value) {
        bitField0_ |= 0x00000002;
        similarity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double similarity = 2;</code>
       */
      public Builder clearSimilarity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        similarity_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ItemSimilarity)
    }

    static {
      defaultInstance = new ItemSimilarity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemSimilarity)
  }

  public interface ItemListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int64 itemIds = 1;
    /**
     * <code>repeated int64 itemIds = 1;</code>
     */
    java.util.List<java.lang.Long> getItemIdsList();
    /**
     * <code>repeated int64 itemIds = 1;</code>
     */
    int getItemIdsCount();
    /**
     * <code>repeated int64 itemIds = 1;</code>
     */
    long getItemIds(int index);
  }
  /**
   * Protobuf type {@code ItemList}
   */
  public static final class ItemList extends
      com.google.protobuf.GeneratedMessage
      implements ItemListOrBuilder {
    // Use ItemList.newBuilder() to construct.
    private ItemList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemList defaultInstance;
    public static ItemList getDefaultInstance() {
      return defaultInstance;
    }

    public ItemList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                itemIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              itemIds_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                itemIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                itemIds_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          itemIds_ = java.util.Collections.unmodifiableList(itemIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.training.spark.proto.Spark.internal_static_ItemList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.training.spark.proto.Spark.internal_static_ItemList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.training.spark.proto.Spark.ItemList.class, org.training.spark.proto.Spark.ItemList.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemList> PARSER =
        new com.google.protobuf.AbstractParser<ItemList>() {
      public ItemList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemList> getParserForType() {
      return PARSER;
    }

    // repeated int64 itemIds = 1;
    public static final int ITEMIDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> itemIds_;
    /**
     * <code>repeated int64 itemIds = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getItemIdsList() {
      return itemIds_;
    }
    /**
     * <code>repeated int64 itemIds = 1;</code>
     */
    public int getItemIdsCount() {
      return itemIds_.size();
    }
    /**
     * <code>repeated int64 itemIds = 1;</code>
     */
    public long getItemIds(int index) {
      return itemIds_.get(index);
    }

    private void initFields() {
      itemIds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < itemIds_.size(); i++) {
        output.writeInt64(1, itemIds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < itemIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(itemIds_.get(i));
        }
        size += dataSize;
        size += 1 * getItemIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.training.spark.proto.Spark.ItemList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.training.spark.proto.Spark.ItemList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.training.spark.proto.Spark.ItemList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.training.spark.proto.Spark.ItemListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.training.spark.proto.Spark.internal_static_ItemList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.training.spark.proto.Spark.internal_static_ItemList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.training.spark.proto.Spark.ItemList.class, org.training.spark.proto.Spark.ItemList.Builder.class);
      }

      // Construct using org.training.spark.proto.Spark.ItemList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.training.spark.proto.Spark.internal_static_ItemList_descriptor;
      }

      public org.training.spark.proto.Spark.ItemList getDefaultInstanceForType() {
        return org.training.spark.proto.Spark.ItemList.getDefaultInstance();
      }

      public org.training.spark.proto.Spark.ItemList build() {
        org.training.spark.proto.Spark.ItemList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.training.spark.proto.Spark.ItemList buildPartial() {
        org.training.spark.proto.Spark.ItemList result = new org.training.spark.proto.Spark.ItemList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          itemIds_ = java.util.Collections.unmodifiableList(itemIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.itemIds_ = itemIds_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.training.spark.proto.Spark.ItemList) {
          return mergeFrom((org.training.spark.proto.Spark.ItemList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.training.spark.proto.Spark.ItemList other) {
        if (other == org.training.spark.proto.Spark.ItemList.getDefaultInstance()) return this;
        if (!other.itemIds_.isEmpty()) {
          if (itemIds_.isEmpty()) {
            itemIds_ = other.itemIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemIdsIsMutable();
            itemIds_.addAll(other.itemIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.training.spark.proto.Spark.ItemList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.training.spark.proto.Spark.ItemList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 itemIds = 1;
      private java.util.List<java.lang.Long> itemIds_ = java.util.Collections.emptyList();
      private void ensureItemIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          itemIds_ = new java.util.ArrayList<java.lang.Long>(itemIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getItemIdsList() {
        return java.util.Collections.unmodifiableList(itemIds_);
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public int getItemIdsCount() {
        return itemIds_.size();
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public long getItemIds(int index) {
        return itemIds_.get(index);
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public Builder setItemIds(
          int index, long value) {
        ensureItemIdsIsMutable();
        itemIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public Builder addItemIds(long value) {
        ensureItemIdsIsMutable();
        itemIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public Builder addAllItemIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureItemIdsIsMutable();
        super.addAll(values, itemIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 itemIds = 1;</code>
       */
      public Builder clearItemIds() {
        itemIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ItemList)
    }

    static {
      defaultInstance = new ItemList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewClickEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewClickEvent_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemSimilarities_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemSimilarities_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemSimilarity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemSimilarity_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013spark.proto\"/\n\rNewClickEvent\022\016\n\006userId" +
      "\030\001 \001(\003\022\016\n\006itemId\030\002 \001(\003\"<\n\020ItemSimilariti" +
      "es\022(\n\017itemSimilarites\030\001 \003(\0132\017.ItemSimila" +
      "rity\"4\n\016ItemSimilarity\022\016\n\006itemId\030\001 \001(\003\022\022" +
      "\n\nsimilarity\030\002 \001(\001\"\033\n\010ItemList\022\017\n\007itemId" +
      "s\030\001 \003(\003B\032\n\030org.training.spark.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewClickEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewClickEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewClickEvent_descriptor,
              new java.lang.String[] { "UserId", "ItemId", });
          internal_static_ItemSimilarities_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ItemSimilarities_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ItemSimilarities_descriptor,
              new java.lang.String[] { "ItemSimilarites", });
          internal_static_ItemSimilarity_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ItemSimilarity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ItemSimilarity_descriptor,
              new java.lang.String[] { "ItemId", "Similarity", });
          internal_static_ItemList_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ItemList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ItemList_descriptor,
              new java.lang.String[] { "ItemIds", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
